name: Acessing Secrets

on:
  push:
    branches: [ main, actions/encrypted-secrets]

jobs:
  access-name-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Reading NAME from repo-secrets
        env: # access secret as environment variable 
          NAME_SECRET: ${{ secrets.SECRET_NAME }}
        run: echo $NAME_SECRET

