name: learn-github-Actions

on:
  push:
    branchs: [action-test-1]

  run-check-in-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run check-in script
        run: |
          chmod +x ./.github/scripts/check-in.sh
          ./.github/scripts/check-in.sh
        shell: bash
