name: sharing-data-bn-jobs

on:
  push:
    branches: [ main, actions/sharing-data-bn-jobs ]

jobs:
  cache-log:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file 
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  
  read-log:
    runs-on: ubuntu-latest
    needs: cache-log
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
      - run: ls .
